steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'me-central1-docker.pkg.dev/portfolio-project-500120/builds-repo/angular-homepage-ssr/nghomepage-ng-ssr:$COMMIT_SHA', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'me-central1-docker.pkg.dev/portfolio-project-500120/builds-repo/angular-homepage-ssr/nghomepage-ng-ssr:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'nghomepage-ng-ssr'
    - '--image'
    - 'me-central1-docker.pkg.dev/portfolio-project-500120/builds-repo/angular-homepage-ssr/nghomepage-ng-ssr:$COMMIT_SHA'
    - '--region'
    - 'me-central1'
images:
- 'me-central1-docker.pkg.dev/portfolio-project-500120/builds-repo/angular-homepage-ssr/nghomepage-ng-ssr:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
